### ISSUE TITLE
Progress Tracker: Kotlin Rewrite

### ISSUE THREAD

**Issue by null2264** [null2264/Mango-Man-Bot#5]
Progress Tracker for [`kotlin` Rewrite](https://github.com/null2264/SpeedrunBot/tree/kotlin)

- [ ] The basics
   - [x] Prefix System (also support slash)
      - [x] Default Prefix (old prefix: `mm!`, currently planned prefix: `src!`)
   - [ ] Bot Rename (planned names: `Hermes`, `Raijin`, `Fujin`, or `Shu`)
   - [ ] New Logo (after bot rename, maybe a combination of name's character and `sr.c` cup?)
   - [x] Command System
      - [ ] Cooldown
   - [ ] Pagination System
      - [ ] List
      - [ ] Named
   - [ ] Database (H2 / SQLite)
   - [ ] Cache System (Redis)
- [ ] SR.C related commands/feature (on halt, waiting for API v2, it's currently undocumented but already used by `sr.c` internally)
   - [ ] RunGet (near real-time verified runs "notification")
      - [ ] Subscription/Follow
      - [ ] RunGet Channel
   - [ ] Pending Runs
      - [ ] Pending Channel (so that non-moderator can use `/pending` command)
   - [ ] Game Info
   - [ ] Category Info
   - [ ] Personal Bests
   - [ ] Runs
   - [ ] Runner Info
   - [ ] Link/Unlink SR.C account (exclusive command for specific servers only?)
   - [ ] Game Moderators
- [ ] Docker Image
