### ISSUE TITLE
Progress Tracker: Python Migration

### ISSUE THREAD

**Issue by null2264** [null2264/Mango-Man-Bot#6]
QoL changes so that I can move the bot more easily

- [x] [`speedrun.py`](https://github.com/null2264/speedrun.py)
    My personal `speedrun.com` (v1) API wrapper
  - [ ] Replace raw requests
- [x] `discord.py` v2
- [x] Migrate to ScyllaDB
  - [x] DB
  - [x] Data
- [x] Docker support
